VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

# VIAL_ENCODERS_ENABLE = yes
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no

QMK_SETTINGS = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
